name: build

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version: [14, 16]  # Exemple d'utilisation d'un matrix avec différentes versions de Node.js (modifier selon le besoin)

    steps:
      - run: npm ci
      - run: npm run build
      - run: npm test